//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHubz.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameHubz.Localization.Resources.TranslationEN", typeof(TranslationEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with ID {1} cannot be deleted because it is already added to {2}..
        /// </summary>
        internal static string CommonValidator_CannotDeleteEntityAlreadyAddedTo {
            get {
                return ResourceManager.GetString("CommonValidator.CannotDeleteEntityAlreadyAddedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with ID: {1} does not belong to {2} with ID: {3}.
        /// </summary>
        internal static string CommonValidator_DoesNotBelongToParentException {
            get {
                return ResourceManager.GetString("CommonValidator.DoesNotBelongToParentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        internal static string CommonValidator_PropertyIsEmpty {
            get {
                return ResourceManager.GetString("CommonValidator.PropertyIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} must be unique..
        /// </summary>
        internal static string CommonValidator_PropertyValueAlreadyExists {
            get {
                return ResourceManager.GetString("CommonValidator.PropertyValueAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token cannot be created..
        /// </summary>
        internal static string Error_TokenCannotBeCreated {
            get {
                return ResourceManager.GetString("Error.TokenCannotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset upload failed.
        /// </summary>
        internal static string Exception_AssetUploadFailedException {
            get {
                return ResourceManager.GetString("Exception.AssetUploadFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute already exists on Taxonomy.
        /// </summary>
        internal static string Exception_AttributeExistsOnTaxonomyException {
            get {
                return ResourceManager.GetString("Exception.AttributeExistsOnTaxonomyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand code already exists.
        /// </summary>
        internal static string Exception_BrandCodeAlreadyExistsException {
            get {
                return ResourceManager.GetString("Exception.BrandCodeAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand group code already exists.
        /// </summary>
        internal static string Exception_BrandGroupCodeAlreadyExistsException {
            get {
                return ResourceManager.GetString("Exception.BrandGroupCodeAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code already exists.
        /// </summary>
        internal static string Exception_CountryCodeAlreadyExistsException {
            get {
                return ResourceManager.GetString("Exception.CountryCodeAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code already exists.
        /// </summary>
        internal static string Exception_CurrencyCodeAlreadyExistsException {
            get {
                return ResourceManager.GetString("Exception.CurrencyCodeAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already in use.
        /// </summary>
        internal static string Exception_EmailAlreadyInUseException {
            get {
                return ResourceManager.GetString("Exception.EmailAlreadyInUseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not retrieved from AD..
        /// </summary>
        internal static string Exception_EmailNotRetrievedException {
            get {
                return ResourceManager.GetString("Exception.EmailNotRetrievedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} already has reference to {1} and there for cannot be deleted..
        /// </summary>
        internal static string Exception_EntityIsAlreadyReferencedException {
            get {
                return ResourceManager.GetString("Exception.EntityIsAlreadyReferencedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity is not found.
        /// </summary>
        internal static string Exception_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Exception.EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity: [{0}] searched by: [{1}] was not found.
        /// </summary>
        internal static string Exception_EntityNotFoundExceptionByCriteria {
            get {
                return ResourceManager.GetString("Exception.EntityNotFoundExceptionByCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity: [{0}] ID: [{1}] was not found.
        /// </summary>
        internal static string Exception_EntityNotFoundExceptionWithDetails {
            get {
                return ResourceManager.GetString("Exception.EntityNotFoundExceptionWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is empty..
        /// </summary>
        internal static string Exception_FileSizeZeroBytesException {
            get {
                return ResourceManager.GetString("Exception.FileSizeZeroBytesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        internal static string Exception_InvalidTokenException {
            get {
                return ResourceManager.GetString("Exception.InvalidTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite token does not exist for &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_InviteTokenNotExistForExistingUserExeption {
            get {
                return ResourceManager.GetString("Exception.InviteTokenNotExistForExistingUserExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple AttributeIds found in ProductAttributes collection: {0}..
        /// </summary>
        internal static string Exception_MultipleProductAttributesWithSameAttributeIdException {
            get {
                return ResourceManager.GetString("Exception.MultipleProductAttributesWithSameAttributeIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute ID: &apos;{0}&apos; does not support multiple values..
        /// </summary>
        internal static string Exception_NotMultipleValueAttrbiuteException {
            get {
                return ResourceManager.GetString("Exception.NotMultipleValueAttrbiuteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two products are not similar..
        /// </summary>
        internal static string Exception_NotSimilarProductsException {
            get {
                return ResourceManager.GetString("Exception.NotSimilarProductsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter error. Parameter: &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_ParameterException {
            get {
                return ResourceManager.GetString("Exception.ParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter error. Invalid token. Parameter: &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_ParameterExceptionInvalidToken {
            get {
                return ResourceManager.GetString("Exception.ParameterExceptionInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is null. Parameter: &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_ParameterNullException {
            get {
                return ResourceManager.GetString("Exception.ParameterNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim not found in token..
        /// </summary>
        internal static string Exception_PrincipalClaimNotFoundException {
            get {
                return ResourceManager.GetString("Exception.PrincipalClaimNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System category cannot be deleted.
        /// </summary>
        internal static string Exception_SystemCategoryCannotBeDeletedException {
            get {
                return ResourceManager.GetString("Exception.SystemCategoryCannotBeDeletedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy is connected to product(s)..
        /// </summary>
        internal static string Exception_TaxonomyIsConnectedToProductException {
            get {
                return ResourceManager.GetString("Exception.TaxonomyIsConnectedToProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User exists in system but is not authorized to access the system or user object is corrupted..
        /// </summary>
        internal static string Exception_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("Exception.UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access to object &apos;{0}&apos; with key &apos;{1}&apos;..
        /// </summary>
        internal static string Exception_UnauthorizedAccessToObjectException {
            get {
                return ResourceManager.GetString("Exception.UnauthorizedAccessToObjectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access..
        /// </summary>
        internal static string Exception_UnauthorizedAccessToServiceException {
            get {
                return ResourceManager.GetString("Exception.UnauthorizedAccessToServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to access requested functionality..
        /// </summary>
        internal static string Exception_UnauthorizedUserModificationException {
            get {
                return ResourceManager.GetString("Exception.UnauthorizedUserModificationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email {0} is already added to system..
        /// </summary>
        internal static string Exception_UserAlreadyAddedException {
            get {
                return ResourceManager.GetString("Exception.UserAlreadyAddedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found by email..
        /// </summary>
        internal static string Exception_UserNotFoundByEmailException {
            get {
                return ResourceManager.GetString("Exception.UserNotFoundByEmailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User token not found in request..
        /// </summary>
        internal static string Exception_UserTokenNotFoundException {
            get {
                return ResourceManager.GetString("Exception.UserTokenNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same product variant already exists.
        /// </summary>
        internal static string Exception_VariantAlreadyExistsException {
            get {
                return ResourceManager.GetString("Exception.VariantAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier code already exists.
        /// </summary>
        internal static string SupplierValidator_CodeAlreadyExists {
            get {
                return ResourceManager.GetString("SupplierValidator.CodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy validation errors.
        /// </summary>
        internal static string TaxonomyValidator_GeneralErrorMessage {
            get {
                return ResourceManager.GetString("TaxonomyValidator.GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy label is required.
        /// </summary>
        internal static string TaxonomyValidator_LabelIsEmpty {
            get {
                return ResourceManager.GetString("TaxonomyValidator.LabelIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy name is required.
        /// </summary>
        internal static string TaxonomyValidator_NameIsEmpty {
            get {
                return ResourceManager.GetString("TaxonomyValidator.NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityId is required.
        /// </summary>
        internal static string TranslationValidator_EntityId {
            get {
                return ResourceManager.GetString("TranslationValidator.EntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type is required.
        /// </summary>
        internal static string TranslationValidator_EntityType {
            get {
                return ResourceManager.GetString("TranslationValidator.EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation for same entity and entity type already exist. .
        /// </summary>
        internal static string TranslationValidator_IsEntityUnique {
            get {
                return ResourceManager.GetString("TranslationValidator.IsEntityUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is required.
        /// </summary>
        internal static string TranslationValidator_Language {
            get {
                return ResourceManager.GetString("TranslationValidator.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name is required.
        /// </summary>
        internal static string TranslationValidator_PropertyName {
            get {
                return ResourceManager.GetString("TranslationValidator.PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string UserValidator_EmailIsEmpty {
            get {
                return ResourceManager.GetString("UserValidator.EmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        internal static string UserValidator_FirstNameIsEmpty {
            get {
                return ResourceManager.GetString("UserValidator.FirstNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User validation errors.
        /// </summary>
        internal static string UserValidator_GeneralErrorMessage {
            get {
                return ResourceManager.GetString("UserValidator.GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        internal static string UserValidator_LastNameIsEmpty {
            get {
                return ResourceManager.GetString("UserValidator.LastNameIsEmpty", resourceCulture);
            }
        }
    }
}
