using GameHubz.DataModels.Enums;

namespace GameHubz.DataModels.Catalog
{
    /// <summary>
    /// A single selectable country. <see cref="Region"/> is the GameHubz region the country
    /// belongs to — selecting a country derives the user's/tournament's region from this value
    /// ("country dictates region"; e.g. RS → EUROPE).
    /// </summary>
    public sealed record CountryInfo(string Code, string Name, string Flag, RegionType Region);

    /// <summary>
    /// Static, hardcoded ISO 3166-1 alpha-2 country catalog with the GameHubz region for each
    /// country. Hardcoded (no external API) so the country→region mapping is deterministic,
    /// offline, and cheap to query. Codes are the canonical stored value on User/Tournament.
    /// </summary>
    public static class CountryCatalog
    {
        public static readonly IReadOnlyList<CountryInfo> All = new List<CountryInfo>
        {
            // ---- Europe ----
            new("AL", "Albania", "🇦🇱", RegionType.EUROPE),
            new("AD", "Andorra", "🇦🇩", RegionType.EUROPE),
            new("AT", "Austria", "🇦🇹", RegionType.EUROPE),
            new("BY", "Belarus", "🇧🇾", RegionType.EUROPE),
            new("BE", "Belgium", "🇧🇪", RegionType.EUROPE),
            new("BA", "Bosnia and Herzegovina", "🇧🇦", RegionType.EUROPE),
            new("BG", "Bulgaria", "🇧🇬", RegionType.EUROPE),
            new("HR", "Croatia", "🇭🇷", RegionType.EUROPE),
            new("CY", "Cyprus", "🇨🇾", RegionType.EUROPE),
            new("CZ", "Czechia", "🇨🇿", RegionType.EUROPE),
            new("DK", "Denmark", "🇩🇰", RegionType.EUROPE),
            new("EE", "Estonia", "🇪🇪", RegionType.EUROPE),
            new("FI", "Finland", "🇫🇮", RegionType.EUROPE),
            new("FR", "France", "🇫🇷", RegionType.EUROPE),
            new("DE", "Germany", "🇩🇪", RegionType.EUROPE),
            new("GR", "Greece", "🇬🇷", RegionType.EUROPE),
            new("HU", "Hungary", "🇭🇺", RegionType.EUROPE),
            new("IS", "Iceland", "🇮🇸", RegionType.EUROPE),
            new("IE", "Ireland", "🇮🇪", RegionType.EUROPE),
            new("IT", "Italy", "🇮🇹", RegionType.EUROPE),
            new("XK", "Kosovo", "🇽🇰", RegionType.EUROPE),
            new("LV", "Latvia", "🇱🇻", RegionType.EUROPE),
            new("LI", "Liechtenstein", "🇱🇮", RegionType.EUROPE),
            new("LT", "Lithuania", "🇱🇹", RegionType.EUROPE),
            new("LU", "Luxembourg", "🇱🇺", RegionType.EUROPE),
            new("MT", "Malta", "🇲🇹", RegionType.EUROPE),
            new("MD", "Moldova", "🇲🇩", RegionType.EUROPE),
            new("MC", "Monaco", "🇲🇨", RegionType.EUROPE),
            new("ME", "Montenegro", "🇲🇪", RegionType.EUROPE),
            new("NL", "Netherlands", "🇳🇱", RegionType.EUROPE),
            new("MK", "North Macedonia", "🇲🇰", RegionType.EUROPE),
            new("NO", "Norway", "🇳🇴", RegionType.EUROPE),
            new("PL", "Poland", "🇵🇱", RegionType.EUROPE),
            new("PT", "Portugal", "🇵🇹", RegionType.EUROPE),
            new("RO", "Romania", "🇷🇴", RegionType.EUROPE),
            new("RU", "Russia", "🇷🇺", RegionType.EUROPE),
            new("SM", "San Marino", "🇸🇲", RegionType.EUROPE),
            new("RS", "Serbia", "🇷🇸", RegionType.EUROPE),
            new("SK", "Slovakia", "🇸🇰", RegionType.EUROPE),
            new("SI", "Slovenia", "🇸🇮", RegionType.EUROPE),
            new("ES", "Spain", "🇪🇸", RegionType.EUROPE),
            new("SE", "Sweden", "🇸🇪", RegionType.EUROPE),
            new("CH", "Switzerland", "🇨🇭", RegionType.EUROPE),
            new("UA", "Ukraine", "🇺🇦", RegionType.EUROPE),
            new("GB", "United Kingdom", "🇬🇧", RegionType.EUROPE),
            new("VA", "Vatican City", "🇻🇦", RegionType.EUROPE),

            // ---- North America (incl. Central America & Caribbean) ----
            new("US", "United States", "🇺🇸", RegionType.NA),
            new("CA", "Canada", "🇨🇦", RegionType.NA),
            new("MX", "Mexico", "🇲🇽", RegionType.NA),
            new("BZ", "Belize", "🇧🇿", RegionType.NA),
            new("CR", "Costa Rica", "🇨🇷", RegionType.NA),
            new("SV", "El Salvador", "🇸🇻", RegionType.NA),
            new("GT", "Guatemala", "🇬🇹", RegionType.NA),
            new("HN", "Honduras", "🇭🇳", RegionType.NA),
            new("NI", "Nicaragua", "🇳🇮", RegionType.NA),
            new("PA", "Panama", "🇵🇦", RegionType.NA),
            new("BS", "Bahamas", "🇧🇸", RegionType.NA),
            new("BB", "Barbados", "🇧🇧", RegionType.NA),
            new("CU", "Cuba", "🇨🇺", RegionType.NA),
            new("DM", "Dominica", "🇩🇲", RegionType.NA),
            new("DO", "Dominican Republic", "🇩🇴", RegionType.NA),
            new("GD", "Grenada", "🇬🇩", RegionType.NA),
            new("HT", "Haiti", "🇭🇹", RegionType.NA),
            new("JM", "Jamaica", "🇯🇲", RegionType.NA),
            new("KN", "Saint Kitts and Nevis", "🇰🇳", RegionType.NA),
            new("LC", "Saint Lucia", "🇱🇨", RegionType.NA),
            new("VC", "Saint Vincent and the Grenadines", "🇻🇨", RegionType.NA),
            new("TT", "Trinidad and Tobago", "🇹🇹", RegionType.NA),
            new("AG", "Antigua and Barbuda", "🇦🇬", RegionType.NA),

            // ---- South America ----
            new("AR", "Argentina", "🇦🇷", RegionType.SA),
            new("BO", "Bolivia", "🇧🇴", RegionType.SA),
            new("BR", "Brazil", "🇧🇷", RegionType.SA),
            new("CL", "Chile", "🇨🇱", RegionType.SA),
            new("CO", "Colombia", "🇨🇴", RegionType.SA),
            new("EC", "Ecuador", "🇪🇨", RegionType.SA),
            new("GY", "Guyana", "🇬🇾", RegionType.SA),
            new("PY", "Paraguay", "🇵🇾", RegionType.SA),
            new("PE", "Peru", "🇵🇪", RegionType.SA),
            new("SR", "Suriname", "🇸🇷", RegionType.SA),
            new("UY", "Uruguay", "🇺🇾", RegionType.SA),
            new("VE", "Venezuela", "🇻🇪", RegionType.SA),

            // ---- Asia (incl. Middle East) ----
            new("AF", "Afghanistan", "🇦🇫", RegionType.ASIA),
            new("AM", "Armenia", "🇦🇲", RegionType.ASIA),
            new("AZ", "Azerbaijan", "🇦🇿", RegionType.ASIA),
            new("BH", "Bahrain", "🇧🇭", RegionType.ASIA),
            new("BD", "Bangladesh", "🇧🇩", RegionType.ASIA),
            new("BT", "Bhutan", "🇧🇹", RegionType.ASIA),
            new("BN", "Brunei", "🇧🇳", RegionType.ASIA),
            new("KH", "Cambodia", "🇰🇭", RegionType.ASIA),
            new("CN", "China", "🇨🇳", RegionType.ASIA),
            new("GE", "Georgia", "🇬🇪", RegionType.ASIA),
            new("HK", "Hong Kong", "🇭🇰", RegionType.ASIA),
            new("IN", "India", "🇮🇳", RegionType.ASIA),
            new("ID", "Indonesia", "🇮🇩", RegionType.ASIA),
            new("IR", "Iran", "🇮🇷", RegionType.ASIA),
            new("IQ", "Iraq", "🇮🇶", RegionType.ASIA),
            new("IL", "Israel", "🇮🇱", RegionType.ASIA),
            new("JP", "Japan", "🇯🇵", RegionType.ASIA),
            new("JO", "Jordan", "🇯🇴", RegionType.ASIA),
            new("KZ", "Kazakhstan", "🇰🇿", RegionType.ASIA),
            new("KW", "Kuwait", "🇰🇼", RegionType.ASIA),
            new("KG", "Kyrgyzstan", "🇰🇬", RegionType.ASIA),
            new("LA", "Laos", "🇱🇦", RegionType.ASIA),
            new("LB", "Lebanon", "🇱🇧", RegionType.ASIA),
            new("MO", "Macau", "🇲🇴", RegionType.ASIA),
            new("MY", "Malaysia", "🇲🇾", RegionType.ASIA),
            new("MV", "Maldives", "🇲🇻", RegionType.ASIA),
            new("MN", "Mongolia", "🇲🇳", RegionType.ASIA),
            new("MM", "Myanmar", "🇲🇲", RegionType.ASIA),
            new("NP", "Nepal", "🇳🇵", RegionType.ASIA),
            new("KP", "North Korea", "🇰🇵", RegionType.ASIA),
            new("OM", "Oman", "🇴🇲", RegionType.ASIA),
            new("PK", "Pakistan", "🇵🇰", RegionType.ASIA),
            new("PS", "Palestine", "🇵🇸", RegionType.ASIA),
            new("PH", "Philippines", "🇵🇭", RegionType.ASIA),
            new("QA", "Qatar", "🇶🇦", RegionType.ASIA),
            new("SA", "Saudi Arabia", "🇸🇦", RegionType.ASIA),
            new("SG", "Singapore", "🇸🇬", RegionType.ASIA),
            new("KR", "South Korea", "🇰🇷", RegionType.ASIA),
            new("LK", "Sri Lanka", "🇱🇰", RegionType.ASIA),
            new("SY", "Syria", "🇸🇾", RegionType.ASIA),
            new("TW", "Taiwan", "🇹🇼", RegionType.ASIA),
            new("TJ", "Tajikistan", "🇹🇯", RegionType.ASIA),
            new("TH", "Thailand", "🇹🇭", RegionType.ASIA),
            new("TL", "Timor-Leste", "🇹🇱", RegionType.ASIA),
            new("TR", "Turkey", "🇹🇷", RegionType.ASIA),
            new("TM", "Turkmenistan", "🇹🇲", RegionType.ASIA),
            new("AE", "United Arab Emirates", "🇦🇪", RegionType.ASIA),
            new("UZ", "Uzbekistan", "🇺🇿", RegionType.ASIA),
            new("VN", "Vietnam", "🇻🇳", RegionType.ASIA),
            new("YE", "Yemen", "🇾🇪", RegionType.ASIA),

            // ---- Africa ----
            new("DZ", "Algeria", "🇩🇿", RegionType.AFRICA),
            new("AO", "Angola", "🇦🇴", RegionType.AFRICA),
            new("BJ", "Benin", "🇧🇯", RegionType.AFRICA),
            new("BW", "Botswana", "🇧🇼", RegionType.AFRICA),
            new("BF", "Burkina Faso", "🇧🇫", RegionType.AFRICA),
            new("BI", "Burundi", "🇧🇮", RegionType.AFRICA),
            new("CM", "Cameroon", "🇨🇲", RegionType.AFRICA),
            new("CV", "Cape Verde", "🇨🇻", RegionType.AFRICA),
            new("CF", "Central African Republic", "🇨🇫", RegionType.AFRICA),
            new("TD", "Chad", "🇹🇩", RegionType.AFRICA),
            new("KM", "Comoros", "🇰🇲", RegionType.AFRICA),
            new("CG", "Congo", "🇨🇬", RegionType.AFRICA),
            new("CD", "DR Congo", "🇨🇩", RegionType.AFRICA),
            new("CI", "Côte d'Ivoire", "🇨🇮", RegionType.AFRICA),
            new("DJ", "Djibouti", "🇩🇯", RegionType.AFRICA),
            new("EG", "Egypt", "🇪🇬", RegionType.AFRICA),
            new("GQ", "Equatorial Guinea", "🇬🇶", RegionType.AFRICA),
            new("ER", "Eritrea", "🇪🇷", RegionType.AFRICA),
            new("SZ", "Eswatini", "🇸🇿", RegionType.AFRICA),
            new("ET", "Ethiopia", "🇪🇹", RegionType.AFRICA),
            new("GA", "Gabon", "🇬🇦", RegionType.AFRICA),
            new("GM", "Gambia", "🇬🇲", RegionType.AFRICA),
            new("GH", "Ghana", "🇬🇭", RegionType.AFRICA),
            new("GN", "Guinea", "🇬🇳", RegionType.AFRICA),
            new("GW", "Guinea-Bissau", "🇬🇼", RegionType.AFRICA),
            new("KE", "Kenya", "🇰🇪", RegionType.AFRICA),
            new("LS", "Lesotho", "🇱🇸", RegionType.AFRICA),
            new("LR", "Liberia", "🇱🇷", RegionType.AFRICA),
            new("LY", "Libya", "🇱🇾", RegionType.AFRICA),
            new("MG", "Madagascar", "🇲🇬", RegionType.AFRICA),
            new("MW", "Malawi", "🇲🇼", RegionType.AFRICA),
            new("ML", "Mali", "🇲🇱", RegionType.AFRICA),
            new("MR", "Mauritania", "🇲🇷", RegionType.AFRICA),
            new("MU", "Mauritius", "🇲🇺", RegionType.AFRICA),
            new("MA", "Morocco", "🇲🇦", RegionType.AFRICA),
            new("MZ", "Mozambique", "🇲🇿", RegionType.AFRICA),
            new("NA", "Namibia", "🇳🇦", RegionType.AFRICA),
            new("NE", "Niger", "🇳🇪", RegionType.AFRICA),
            new("NG", "Nigeria", "🇳🇬", RegionType.AFRICA),
            new("RW", "Rwanda", "🇷🇼", RegionType.AFRICA),
            new("ST", "São Tomé and Príncipe", "🇸🇹", RegionType.AFRICA),
            new("SN", "Senegal", "🇸🇳", RegionType.AFRICA),
            new("SC", "Seychelles", "🇸🇨", RegionType.AFRICA),
            new("SL", "Sierra Leone", "🇸🇱", RegionType.AFRICA),
            new("SO", "Somalia", "🇸🇴", RegionType.AFRICA),
            new("ZA", "South Africa", "🇿🇦", RegionType.AFRICA),
            new("SS", "South Sudan", "🇸🇸", RegionType.AFRICA),
            new("SD", "Sudan", "🇸🇩", RegionType.AFRICA),
            new("TZ", "Tanzania", "🇹🇿", RegionType.AFRICA),
            new("TG", "Togo", "🇹🇬", RegionType.AFRICA),
            new("TN", "Tunisia", "🇹🇳", RegionType.AFRICA),
            new("UG", "Uganda", "🇺🇬", RegionType.AFRICA),
            new("ZM", "Zambia", "🇿🇲", RegionType.AFRICA),
            new("ZW", "Zimbabwe", "🇿🇼", RegionType.AFRICA),

            // ---- Oceania ----
            new("AU", "Australia", "🇦🇺", RegionType.OCEANIA),
            new("NZ", "New Zealand", "🇳🇿", RegionType.OCEANIA),
            new("FJ", "Fiji", "🇫🇯", RegionType.OCEANIA),
            new("PG", "Papua New Guinea", "🇵🇬", RegionType.OCEANIA),
            new("SB", "Solomon Islands", "🇸🇧", RegionType.OCEANIA),
            new("VU", "Vanuatu", "🇻🇺", RegionType.OCEANIA),
            new("WS", "Samoa", "🇼🇸", RegionType.OCEANIA),
            new("TO", "Tonga", "🇹🇴", RegionType.OCEANIA),
            new("KI", "Kiribati", "🇰🇮", RegionType.OCEANIA),
            new("FM", "Micronesia", "🇫🇲", RegionType.OCEANIA),
            new("MH", "Marshall Islands", "🇲🇭", RegionType.OCEANIA),
            new("NR", "Nauru", "🇳🇷", RegionType.OCEANIA),
            new("PW", "Palau", "🇵🇼", RegionType.OCEANIA),
            new("TV", "Tuvalu", "🇹🇻", RegionType.OCEANIA),
        };

        private static readonly Dictionary<string, CountryInfo> ByCode =
            All.ToDictionary(c => c.Code, StringComparer.OrdinalIgnoreCase);

        /// <summary>Returns the country for an ISO code, or null when the code is unknown/null.</summary>
        public static CountryInfo? Get(string? code)
            => !string.IsNullOrWhiteSpace(code) && ByCode.TryGetValue(code, out var info) ? info : null;

        /// <summary>True when the code maps to a known catalog entry.</summary>
        public static bool IsValid(string? code) => Get(code) != null;

        /// <summary>The GameHubz region a country belongs to, or null for unknown/null codes.</summary>
        public static RegionType? RegionFor(string? code) => Get(code)?.Region;
    }
}
